import { Language } from './translations';

export interface TarotCard {
  number: number;
  name: Record<Language, string>;
  description: Record<Language, string>;
}

export const tarotCards: TarotCard[] = [
  {
    number: 0,
    name: {
      en: 'The Fool',
      es: 'El Loco',
      it: 'Il Matto',
      de: 'Der Narr',
      zh: '愚者',
      ja: '愚者',
      fr: 'Le Mat',
    },
    description: {
      en: 'New beginnings, innocence, spontaneity. A leap of faith into the unknown.',
      es: 'Nuevos comienzos, inocencia, espontaneidad. Un salto de fe hacia lo desconocido.',
      it: 'Nuovi inizi, innocenza, spontaneità. Un salto di fede verso l\'ignoto.',
      de: 'Neuanfang, Unschuld, Spontaneität. Ein Vertrauenssprung ins Unbekannte.',
      zh: '新的开始、天真、自发性。向未知的信仰飞跃。',
      ja: '新しい始まり、無邪気さ、自発性。未知への信仰の飛躍。',
      fr: 'Nouveaux départs, innocence, spontanéité. Un saut de foi vers l\'inconnu.',
    },
  },
  {
    number: 1,
    name: {
      en: 'The Magician',
      es: 'El Mago',
      it: 'Il Bagatto',
      de: 'Der Magier',
      zh: '魔术师',
      ja: '魔術師',
      fr: 'Le Bateleur',
    },
    description: {
      en: 'Manifestation, resourcefulness, power. The ability to transform ideas into reality.',
      es: 'Manifestación, ingenio, poder. La capacidad de transformar ideas en realidad.',
      it: 'Manifestazione, intraprendenza, potere. La capacità di trasformare le idee in realtà.',
      de: 'Manifestation, Einfallsreichtum, Macht. Die Fähigkeit, Ideen in Realität zu verwandeln.',
      zh: '显化、足智多谋、力量。将想法转化为现实的能力。',
      ja: '顕現、機知、力。アイデアを現実に変える能力。',
      fr: 'Manifestation, ingéniosité, pouvoir. La capacité de transformer les idées en réalité.',
    },
  },
  {
    number: 2,
    name: {
      en: 'The High Priestess',
      es: 'La Papisa',
      it: 'La Papessa',
      de: 'Die Hohepriesterin',
      zh: '女祭司',
      ja: '女教皇',
      fr: 'La Papesse',
    },
    description: {
      en: 'Intuition, mystery, inner knowledge. Trust your inner voice and hidden wisdom.',
      es: 'Intuición, misterio, conocimiento interior. Confía en tu voz interior y sabiduría oculta.',
      it: 'Intuizione, mistero, conoscenza interiore. Fidati della tua voce interiore e della saggezza nascosta.',
      de: 'Intuition, Geheimnis, inneres Wissen. Vertraue deiner inneren Stimme und verborgenen Weisheit.',
      zh: '直觉、神秘、内在知识。相信你的内心声音和隐藏的智慧。',
      ja: '直感、神秘、内なる知識。内なる声と隠された知恵を信じてください。',
      fr: 'Intuition, mystère, connaissance intérieure. Faites confiance à votre voix intérieure et à la sagesse cachée.',
    },
  },
  {
    number: 3,
    name: {
      en: 'The Empress',
      es: 'La Emperatriz',
      it: 'L\'Imperatrice',
      de: 'Die Kaiserin',
      zh: '皇后',
      ja: '女帝',
      fr: 'L\'Impératrice',
    },
    description: {
      en: 'Fertility, abundance, nature. Creative expression and nurturing energy.',
      es: 'Fertilidad, abundancia, naturaleza. Expresión creativa y energía nutritiva.',
      it: 'Fertilità, abbondanza, natura. Espressione creativa ed energia nutriente.',
      de: 'Fruchtbarkeit, Fülle, Natur. Kreativer Ausdruck und nährende Energie.',
      zh: '生育、丰盛、自然。创意表达和养育能量。',
      ja: '豊穣、豊かさ、自然。創造的表現と養育のエネルギー。',
      fr: 'Fertilité, abondance, nature. Expression créative et énergie nourricière.',
    },
  },
  {
    number: 4,
    name: {
      en: 'The Emperor',
      es: 'El Emperador',
      it: 'L\'Imperatore',
      de: 'Der Kaiser',
      zh: '皇帝',
      ja: '皇帝',
      fr: 'L\'Empereur',
    },
    description: {
      en: 'Authority, structure, control. Establishing order and building solid foundations.',
      es: 'Autoridad, estructura, control. Establecer orden y construir bases sólidas.',
      it: 'Autorità, struttura, controllo. Stabilire l\'ordine e costruire solide fondamenta.',
      de: 'Autorität, Struktur, Kontrolle. Ordnung schaffen und solide Grundlagen bauen.',
      zh: '权威、结构、控制。建立秩序和打下坚实基础。',
      ja: '権威、構造、支配。秩序を確立し、堅固な基盤を築く。',
      fr: 'Autorité, structure, contrôle. Établir l\'ordre et construire des fondations solides.',
    },
  },
  {
    number: 5,
    name: {
      en: 'The Hierophant',
      es: 'El Papa',
      it: 'Il Papa',
      de: 'Der Hierophant',
      zh: '教皇',
      ja: '法王',
      fr: 'Le Pape',
    },
    description: {
      en: 'Tradition, conformity, spiritual wisdom. Learning from established teachings.',
      es: 'Tradición, conformidad, sabiduría espiritual. Aprender de las enseñanzas establecidas.',
      it: 'Tradizione, conformità, saggezza spirituale. Imparare dagli insegnamenti consolidati.',
      de: 'Tradition, Konformität, spirituelle Weisheit. Von etablierten Lehren lernen.',
      zh: '传统、顺从、精神智慧。从既定教导中学习。',
      ja: '伝統、順応、精神的知恵。確立された教えから学ぶ。',
      fr: 'Tradition, conformité, sagesse spirituelle. Apprendre des enseignements établis.',
    },
  },
  {
    number: 6,
    name: {
      en: 'The Lovers',
      es: 'Los Enamorados',
      it: 'Gli Amanti',
      de: 'Die Liebenden',
      zh: '恋人',
      ja: '恋人',
      fr: 'L\'Amoureux',
    },
    description: {
      en: 'Doubt, indecision, immaturity. A crossroads requiring careful choice between paths.',
      es: 'Duda, indecisión, inmadurez. Una encrucijada que requiere una elección cuidadosa entre caminos.',
      it: 'Dubbio, indecisione, immaturità. Un bivio che richiede una scelta attenta tra i percorsi.',
      de: 'Zweifel, Unentschlossenheit, Unreife. Ein Scheideweg, der eine sorgfältige Wahl zwischen Wegen erfordert.',
      zh: '怀疑、犹豫不决、不成熟。需要在道路之间做出谨慎选择的十字路口。',
      ja: '疑い、優柔不断、未熟さ。道の間で慎重な選択を必要とする岐路。',
      fr: 'Doute, indécision, immaturité. Un carrefour nécessitant un choix prudent entre les chemins.',
    },
  },
  {
    number: 7,
    name: {
      en: 'The Chariot',
      es: 'El Carro',
      it: 'Il Carro',
      de: 'Der Wagen',
      zh: '战车',
      ja: '戦車',
      fr: 'Le Chariot',
    },
    description: {
      en: 'Determination, willpower, victory. Moving forward with confidence and control.',
      es: 'Determinación, fuerza de voluntad, victoria. Avanzar con confianza y control.',
      it: 'Determinazione, forza di volontà, vittoria. Andare avanti con fiducia e controllo.',
      de: 'Entschlossenheit, Willenskraft, Sieg. Mit Zuversicht und Kontrolle vorwärts gehen.',
      zh: '决心、意志力、胜利。自信且有控制地前进。',
      ja: '決意、意志力、勝利。自信と制御を持って前進する。',
      fr: 'Détermination, volonté, victoire. Avancer avec confiance et contrôle.',
    },
  },
  {
    number: 8,
    name: {
      en: 'Justice',
      es: 'La Justicia',
      it: 'La Giustizia',
      de: 'Die Gerechtigkeit',
      zh: '正义',
      ja: '正義',
      fr: 'La Justice',
    },
    description: {
      en: 'Fairness, truth, cause and effect. Balance and accountability in all things.',
      es: 'Equidad, verdad, causa y efecto. Equilibrio y responsabilidad en todas las cosas.',
      it: 'Equità, verità, causa ed effetto. Equilibrio e responsabilità in tutte le cose.',
      de: 'Fairness, Wahrheit, Ursache und Wirkung. Balance und Verantwortung in allen Dingen.',
      zh: '公平、真相、因果。万事皆有平衡与责任。',
      ja: '公正、真実、因果。すべてにおけるバランスと責任。',
      fr: 'Équité, vérité, cause et effet. Équilibre et responsabilité en toutes choses.',
    },
  },
  {
    number: 9,
    name: {
      en: 'The Hermit',
      es: 'El Ermitaño',
      it: 'L\'Eremita',
      de: 'Der Eremit',
      zh: '隐士',
      ja: '隠者',
      fr: 'L\'Hermite',
    },
    description: {
      en: 'Introspection, solitude, inner guidance. Seeking wisdom through contemplation.',
      es: 'Introspección, soledad, guía interior. Buscar sabiduría a través de la contemplación.',
      it: 'Introspezione, solitudine, guida interiore. Cercare la saggezza attraverso la contemplazione.',
      de: 'Innenschau, Einsamkeit, innere Führung. Weisheit durch Kontemplation suchen.',
      zh: '内省、孤独、内在引导。通过沉思寻求智慧。',
      ja: '内省、孤独、内なる導き。瞑想を通じて知恵を求める。',
      fr: 'Introspection, solitude, guidance intérieure. Chercher la sagesse par la contemplation.',
    },
  },
  {
    number: 10,
    name: {
      en: 'Wheel of Fortune',
      es: 'La Rueda de la Fortuna',
      it: 'La Ruota della Fortuna',
      de: 'Das Rad des Schicksals',
      zh: '命运之轮',
      ja: '運命の輪',
      fr: 'La Roue de Fortune',
    },
    description: {
      en: 'Cycles, destiny, turning points. Life\'s constant change and evolution.',
      es: 'Ciclos, destino, puntos de inflexión. El cambio constante y la evolución de la vida.',
      it: 'Cicli, destino, punti di svolta. Il costante cambiamento e l\'evoluzione della vita.',
      de: 'Zyklen, Schicksal, Wendepunkte. Der ständige Wandel und die Evolution des Lebens.',
      zh: '循环、命运、转折点。生命的持续变化与进化。',
      ja: 'サイクル、運命、転換点。人生の絶え間ない変化と進化。',
      fr: 'Cycles, destin, tournants. Le changement constant et l\'évolution de la vie.',
    },
  },
  {
    number: 11,
    name: {
      en: 'Strength',
      es: 'La Fuerza',
      it: 'La Forza',
      de: 'Die Kraft',
      zh: '力量',
      ja: '力',
      fr: 'La Force',
    },
    description: {
      en: 'Courage, patience, inner strength. Mastering your inner world with compassion.',
      es: 'Coraje, paciencia, fuerza interior. Dominar tu mundo interior con compasión.',
      it: 'Coraggio, pazienza, forza interiore. Padroneggiare il tuo mondo interiore con compassione.',
      de: 'Mut, Geduld, innere Stärke. Die innere Welt mit Mitgefühl beherrschen.',
      zh: '勇气、耐心、内在力量。用慈悲掌控你的内心世界。',
      ja: '勇気、忍耐、内なる強さ。思いやりを持って内なる世界を支配する。',
      fr: 'Courage, patience, force intérieure. Maîtriser votre monde intérieur avec compassion.',
    },
  },
  {
    number: 12,
    name: {
      en: 'The Hanged Man',
      es: 'El Colgado',
      it: 'L\'Appeso',
      de: 'Der Gehängte',
      zh: '倒吊人',
      ja: '吊された男',
      fr: 'Le Pendu',
    },
    description: {
      en: 'Surrender, new perspective, letting go. Seeing things from a different angle.',
      es: 'Rendición, nueva perspectiva, soltar. Ver las cosas desde un ángulo diferente.',
      it: 'Resa, nuova prospettiva, lasciar andare. Vedere le cose da un angolo diverso.',
      de: 'Hingabe, neue Perspektive, Loslassen. Die Dinge aus einem anderen Blickwinkel sehen.',
      zh: '臣服、新视角、放下。从不同角度看事物。',
      ja: '降伏、新しい視点、手放し。異なる角度から物事を見る。',
      fr: 'Abandon, nouvelle perspective, lâcher prise. Voir les choses sous un angle différent.',
    },
  },
  {
    number: 13,
    name: {
      en: 'Death',
      es: 'La Muerte',
      it: 'La Morte',
      de: 'Der Tod',
      zh: '死神',
      ja: '死',
      fr: 'La Mort',
    },
    description: {
      en: 'Transformation, endings, new beginnings. The end of one chapter and start of another.',
      es: 'Transformación, finales, nuevos comienzos. El fin de un capítulo y el inicio de otro.',
      it: 'Trasformazione, finali, nuovi inizi. La fine di un capitolo e l\'inizio di un altro.',
      de: 'Transformation, Enden, Neuanfänge. Das Ende eines Kapitels und der Beginn eines neuen.',
      zh: '转变、结束、新开始。一个篇章的结束和另一个的开始。',
      ja: '変容、終わり、新しい始まり。一つの章の終わりと別の章の始まり。',
      fr: 'Transformation, fins, nouveaux départs. La fin d\'un chapitre et le début d\'un autre.',
    },
  },
  {
    number: 14,
    name: {
      en: 'Temperance',
      es: 'La Templanza',
      it: 'La Temperanza',
      de: 'Die Mäßigkeit',
      zh: '节制',
      ja: '節制',
      fr: 'Tempérance',
    },
    description: {
      en: 'Balance, moderation, patience. Finding middle ground and inner peace.',
      es: 'Equilibrio, moderación, paciencia. Encontrar el punto medio y la paz interior.',
      it: 'Equilibrio, moderazione, pazienza. Trovare la via di mezzo e la pace interiore.',
      de: 'Balance, Mäßigung, Geduld. Den Mittelweg und inneren Frieden finden.',
      zh: '平衡、节制、耐心。找到中间地带和内心平静。',
      ja: 'バランス、節度、忍耐。中庸と内なる平和を見つける。',
      fr: 'Équilibre, modération, patience. Trouver le juste milieu et la paix intérieure.',
    },
  },
  {
    number: 15,
    name: {
      en: 'The Devil',
      es: 'El Diablo',
      it: 'Il Diavolo',
      de: 'Der Teufel',
      zh: '恶魔',
      ja: '悪魔',
      fr: 'Le Diable',
    },
    description: {
      en: 'Shadow self, attachment, materialism. Recognizing what binds you.',
      es: 'Yo sombra, apego, materialismo. Reconocer lo que te ata.',
      it: 'Ombra interiore, attaccamento, materialismo. Riconoscere ciò che ti lega.',
      de: 'Schattenseite, Anhaftung, Materialismus. Erkennen, was Sie bindet.',
      zh: '阴暗面、执着、物质主义。认识到束缚你的东西。',
      ja: '影の自己、執着、物質主義。あなたを縛るものを認識する。',
      fr: 'Ombre intérieure, attachement, matérialisme. Reconnaître ce qui vous lie.',
    },
  },
  {
    number: 16,
    name: {
      en: 'The Tower',
      es: 'La Torre',
      it: 'La Torre',
      de: 'Der Turm',
      zh: '塔',
      ja: '塔',
      fr: 'La Maison Dieu',
    },
    description: {
      en: 'Sudden change, upheaval, revelation. Breaking down false structures.',
      es: 'Cambio repentino, agitación, revelación. Derribar estructuras falsas.',
      it: 'Cambiamento improvviso, sconvolgimento, rivelazione. Abbattere false strutture.',
      de: 'Plötzliche Veränderung, Umwälzung, Offenbarung. Falsche Strukturen einreißen.',
      zh: '突变、剧变、启示。打破虚假结构。',
      ja: '突然の変化、激変、啓示。偽りの構造を壊す。',
      fr: 'Changement soudain, bouleversement, révélation. Détruire les fausses structures.',
    },
  },
  {
    number: 17,
    name: {
      en: 'The Star',
      es: 'La Estrella',
      it: 'La Stella',
      de: 'Der Stern',
      zh: '星星',
      ja: '星',
      fr: 'L\'Étoile',
    },
    description: {
      en: 'Hope, inspiration, serenity. Renewed faith and spiritual guidance.',
      es: 'Esperanza, inspiración, serenidad. Fe renovada y guía espiritual.',
      it: 'Speranza, ispirazione, serenità. Fede rinnovata e guida spirituale.',
      de: 'Hoffnung, Inspiration, Gelassenheit. Erneuerter Glaube und spirituelle Führung.',
      zh: '希望、灵感、宁静。重新获得信仰和精神指引。',
      ja: '希望、インスピレーション、静けさ。新たな信仰と精神的導き。',
      fr: 'Espoir, inspiration, sérénité. Foi renouvelée et guidance spirituelle.',
    },
  },
  {
    number: 18,
    name: {
      en: 'The Moon',
      es: 'La Luna',
      it: 'La Luna',
      de: 'Der Mond',
      zh: '月亮',
      ja: '月',
      fr: 'La Lune',
    },
    description: {
      en: 'Illusion, intuition, the unconscious. Navigating through uncertainty.',
      es: 'Ilusión, intuición, el inconsciente. Navegar a través de la incertidumbre.',
      it: 'Illusione, intuizione, l\'inconscio. Navigare attraverso l\'incertezza.',
      de: 'Illusion, Intuition, das Unbewusste. Durch Unsicherheit navigieren.',
      zh: '幻觉、直觉、潜意识。穿越不确定性。',
      ja: '幻想、直感、無意識。不確実性を通して航行する。',
      fr: 'Illusion, intuition, l\'inconscient. Naviguer à travers l\'incertitude.',
    },
  },
  {
    number: 19,
    name: {
      en: 'The Sun',
      es: 'El Sol',
      it: 'Il Sole',
      de: 'Die Sonne',
      zh: '太阳',
      ja: '太陽',
      fr: 'Le Soleil',
    },
    description: {
      en: 'Joy, success, vitality. Radiant energy and positive outcomes.',
      es: 'Alegría, éxito, vitalidad. Energía radiante y resultados positivos.',
      it: 'Gioia, successo, vitalità. Energia radiante e risultati positivi.',
      de: 'Freude, Erfolg, Vitalität. Strahlende Energie und positive Ergebnisse.',
      zh: '喜悦、成功、活力。光芒四射的能量和积极的结果。',
      ja: '喜び、成功、活力。輝くエネルギーと前向きな結果。',
      fr: 'Joie, succès, vitalité. Énergie rayonnante et résultats positifs.',
    },
  },
  {
    number: 20,
    name: {
      en: 'Judgement',
      es: 'El Juicio',
      it: 'Il Giudizio',
      de: 'Das Gericht',
      zh: '审判',
      ja: '審判',
      fr: 'Le Jugement',
    },
    description: {
      en: 'Rebirth, inner calling, absolution. Awakening to your true purpose.',
      es: 'Renacimiento, llamado interior, absolución. Despertar a tu verdadero propósito.',
      it: 'Rinascita, chiamata interiore, assoluzione. Risvegliarsi al proprio vero scopo.',
      de: 'Wiedergeburt, innere Berufung, Absolution. Erwachen zu Ihrem wahren Zweck.',
      zh: '重生、内在召唤、赦免。觉醒于你真正的目的。',
      ja: '再生、内なる呼びかけ、赦し。真の目的への目覚め。',
      fr: 'Renaissance, appel intérieur, absolution. Éveil à votre vrai but.',
    },
  },
  {
    number: 21,
    name: {
      en: 'The World',
      es: 'El Mundo',
      it: 'Il Mondo',
      de: 'Die Welt',
      zh: '世界',
      ja: '世界',
      fr: 'Le Monde',
    },
    description: {
      en: 'Completion, integration, accomplishment. The successful end of a cycle.',
      es: 'Finalización, integración, logro. El fin exitoso de un ciclo.',
      it: 'Completamento, integrazione, realizzazione. La conclusione di successo di un ciclo.',
      de: 'Vollendung, Integration, Erfolg. Das erfolgreiche Ende eines Zyklus.',
      zh: '完成、整合、成就。一个周期的成功结束。',
      ja: '完成、統合、達成。サイクルの成功裏の終了。',
      fr: 'Achèvement, intégration, accomplissement. La fin réussie d\'un cycle.',
    },
  },
  {
    number: 22,
    name: {
      en: 'The Fool (Master)',
      es: 'El Loco (Maestro)',
      it: 'Il Matto (Maestro)',
      de: 'Der Narr (Meister)',
      zh: '愚者（大师）',
      ja: '愚者（マスター）',
      fr: 'Le Mat (Maître)',
    },
    description: {
      en: 'Ultimate potential, unlimited possibilities. The master builder\'s journey comes full circle.',
      es: 'Potencial máximo, posibilidades ilimitadas. El viaje del constructor maestro llega a su círculo completo.',
      it: 'Potenziale massimo, possibilità illimitate. Il viaggio del costruttore maestro si chiude.',
      de: 'Ultimatives Potenzial, unbegrenzte Möglichkeiten. Die Reise des Meisterbaumeisters vollendet sich.',
      zh: '终极潜能、无限可能。大师建造者的旅程完成了圆满循环。',
      ja: '究極の可能性、無限の可能性。マスタービルダーの旅は完全な円を描きます。',
      fr: 'Potentiel ultime, possibilités illimitées. Le voyage du maître bâtisseur boucle la boucle.',
    },
  },
];

export const getTarotCard = (number: number): TarotCard | null => {
  // Map numerology numbers to tarot cards
  // Direct mapping for Major Arcana 0-21
  if (number >= 0 && number <= 21) {
    return tarotCards.find(card => card.number === number) || null;
  }
  // Special cases for master numbers mapping to specific cards
  if (number === 22) return tarotCards.find(card => card.number === 22) || tarotCards[0]; // The Fool (Master)
  if (number === 33) return tarotCards.find(card => card.number === 6) || null; // The Lovers (3+3)
  if (number === 44) return tarotCards.find(card => card.number === 8) || null; // Justice (4+4)
  return null;
};
